name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows you to trigger the workflow manually

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install
  
      - name: Build the app
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public